services:
  - type: web
    name: django-blog
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn blog.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WEB_CONCURRENCY
        value: 4
